[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "chromium", "nss", "freetype", "harfbuzz"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/root/.nix-profile/bin/chromium"
